server:
  port: 8088
  servlet:
    context-path: /crm
    jsp:
      init-parameters:
        development: true
    encoding:
        force: true
        charset: UTF-8
        enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crm2008?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    druid:
      filters: stat,wall,slf4j
      aop-patterns: "com.QH.crm.settings.mapper.*,com.QH.crm.workbench.mapper.*"  #Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      timeBetweenEvictionRunsMillis: 60000
      min-evictable-idle-time-millis: 300000
      web-stat-filter:
        enabled: true
        url-pattern: /druid/*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
      filter:
        stat:
          mergeSql: true
          log-slow-sql: true
          slow-sql-millis: 3000
          enabled: true
          db-type: mysql
        wall:
          config:
            multi-statement-allow: false
          enabled: true
          db-type: mysql
        slf4j:
          statement-executable-sql-log-enable: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
      enabled: true

  web:
    resources:
      static-locations: classpath:/
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:/mapper/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#开发使用
#decorator:
#  datasource:
#    p6spy:
#      logging: slf4j

#生产使用
#decorator:
# datasource:
#  datasource:
#    p6spy:
#      logging: file
#      log-file: spy.log
#      log-format: executionTime:%(executionTime) | sql:%(sqlSingleLine)

